#!/usr/bin/env node

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import openapiTS, { astToString } from "openapi-typescript";

const args = process.argv.slice(2);

function getArg(name) {
  const direct = args.find((arg) => arg.startsWith(`${name}=`));

  if (direct) {
    return direct.slice(name.length + 1);
  }

  const index = args.indexOf(name);

  if (index !== -1) {
    return args[index + 1];
  }

  return undefined;
}

const baseUrl = (getArg("--base-url") ?? process.env.METABASE_BASE_URL ?? "https://metabase.portals-mem.com").replace(/\/+$/, "");
const apiKey = getArg("--api-key") ?? process.env.METABASE_API_KEY;
const endpoint = new URL("/api/docs/openapi.json", `${baseUrl}/`);

const headers = new Headers({
  Accept: "application/json"
});

if (apiKey) {
  headers.set("x-api-key", apiKey);
}

const response = await fetch(endpoint, { headers });

if (!response.ok) {
  throw new Error(`Failed to fetch OpenAPI spec from ${endpoint}: ${response.status} ${response.statusText}`);
}

const schema = await response.json();
const ast = await openapiTS(schema, {
  alphabetize: true
});
const contents = astToString(ast);
const outputPath = path.resolve(process.cwd(), "src/generated/openapi.ts");

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  [
    "/* eslint-disable */",
    "// This file is generated by scripts/sync-openapi.mjs.",
    `// Source: ${endpoint}`,
    "",
    contents
  ].join("\n"),
  "utf8"
);

process.stdout.write(`Wrote ${outputPath}\n`);
